#!/usr/bin/env ruby
# -*- mode: ruby; coding: utf-8-unix; indent-tabs-mode: nil -*-
#
# Author::    Takeru Naito (mailto:takeru.naito@gmail.com)
# Copyright:: Copyright (c) 2008 Takeru Naito
# License::   Distributes under the same terms as Ruby
#
#
#=
#emacswiki の anything (など)が更新されていたら、
#ローカルのファイルを置き換えます。
#
#==
#使用方法
#
#% ./update-anything
#

require 'rubygems'
require 'mechanize'
require 'logger'

class UpdateAnything
  def initialize(opts = {})
    @agent  = WWW::Mechanize.new do |a|
      a.max_history      = 1
      a.user_agent_alias = 'Mac FireFox'
      a.log              = Logger.new(opts[:log_output])
      a.log.level        = opts[:log_level]
    end
  end

  def run
    analyze_el_page
  end

  private
  def fetch(uri)
    begin
      sleep 2 #wait
      @agent.get(uri)
    rescue Timeout::Error
      @agent.log.warn "  caught Timeout::Error !"
      retry
    rescue WWW::Mechanize::ResponseCodeError => e
      case e.response_code
      when "502"
        @agent.log.warn "  caught Net::HTTPBadGateway !"
        retry
      when "404"
        @agent.log.warn "  caught Net::HTTPNotFound !"
      else
        @agent.log.warn "  caught Excepcion !" + e.response_code
      end
    end
  end

  def analyze_el_page
    url_base = "http://www.emacswiki.org/cgi-bin/wiki/download/"
    anythings = Dir::glob("*el")

    anythings.each do |fname|
      local_version = detect_version(File::open(fname).read)

      remote = fetch("#{url_base}#{fname}").body
      remote_version = detect_version(remote)

      puts [
        "\n#{fname}",
        "\tlocal_version  => #{local_version}",
        "\tremote_version => #{remote_version}",
      ].join("\n")

      unless local_version == remote_version
        puts "update detect.\n" + "updating..."
        File::open(fname, 'w') do |f|
          f.write remote
        end
        puts "done."
      end
    end
  end

  def detect_version(str)
    version = nil
    version_regexp = Regexp::union(
      /version.+(\<.+\>)/, # anything-config.el
      /\$Id.+(\d+\.\d+)/   # other
      )
    str.each do |line|
      if line =~ version_regexp
        version ||= Regexp::last_match[1] || Regexp::last_match[2]
      end
    end
    version
  end

end

if $0 == __FILE__
  require 'optparse'

  opts = {
    :log_output => STDERR,
    :log_level  => Logger::WARN
  }

  OptionParser.new do |parser|
    parser.instance_eval do
      on('-v', '--verbose', 'verbose mode') do |arg|
        opts[:log_level] = Logger::INFO
      end

      on('-d', '--debug', 'debug mode') do |arg|
        opts[:log_level]  = Logger::DEBUG
      end
      parse!
    end
  end

  UpdateAnything.new(opts).run
end
